### ISSUE TITLE
Musiques qui bug

### ISSUE THREAD

**Issue by Pierraurelien** [Amphaal/AudioTube#1]
https://www.youtube.com/watch?v=lkkHtuTdIj4 
https://www.youtube.com/watch?v=NjaxuNuCAH8 
https://www.youtube.com/watch?v=f7EJbyPylKc
https://www.youtube.com/watch?v=ELhoHQEGGUc 
https://www.youtube.com/watch?v=viVLQtfOUPc 
https://www.youtube.com/watch?v=2VWkeSF0FGw

**Comment by gg-vara** [comment]
Related to the upstream library https://github.com/Tyrrrz/YoutubeExplode/issues/349, waiting for a fix :)
